site_name: Внедрение стандартов Worldskills Russia в образовательный процесс Университета

nav:
  - Описание проекта: index.md
  - Точка отсчета:
    - «Формирование системы практико-ориентированной подготовки кадров для предприятий и организаций региона»:
      - Проект : start_point/project_1.md
      - Результаты реализации проекта в 2013-2015 г. : start_point/project_1_result.md
    - Отчет О реализции проекта по подготовке высококвалифицированных кадров для предприятий и организаций регионов «кадры для регионов»: start_point/employment_for_region.md


    

theme:
  name: 'material'
  language: 'ru'
  palette:
    primary: 'Blue'
    accent: 'Red'
  feature:
    tabs: true
  # logo: images/logo/logo_cut.png
