site_name: Внедрение стандартов Worldskills Russia в образовательный процесс Университета

markdown_extensions:
  - toc:
      permalink: true
  - meta


nav:
  - Описание проекта: 
    - Описание проекта: index.md
    - Партнеры по реализации проекта: partners.md
    - Точка отсчета: start_point_link.md
  - Точка отсчета:
    - Кадры для региона:
      - «Формирование системы практико-ориентированной подготовки кадров для предприятий и организаций региона»:
        - Проект : start_point/project_1.md
        - Результаты реализации проекта в 2013-2015 г. : start_point/project_1_result.md
      - Отчет О реализции проекта по подготовке высококвалифицированных кадров для предприятий и организаций регионов «кадры для регионов»: start_point/employment_for_region.md
      - Система определения контрольных цифр приема Ханты-Мансийского автономного округа – Югры: start_point/ktc.md
      - Целевой прием в Югорский государственный университет: start_point/targeted_admission.md

    - Независимая оценка качества:
      - Проектирование образовательных программ в интересах предприятий-партнеров: start_point/project_oop.md
      - Профессиональные стандарты, нефтегазовое дело, структурирование компетенций, качество освоения образовательной программы, объективизация: start_point/other/prof.md
      - Экспертный комплекс объективного оценивания качества освоения образовательной программы по направлению подготовки: start_point/other/tz_1.md
      - Структура модели экспертного оценивания параметров оптимизации внутренней структуры компетенций: start_point/other/bd.md

    - Федеральный этап конкурса «Славим человека труда:
      - Конкурс "Славим человека труда": start_point/work_human.md

    - Участие в мероприятиях Ворлдскиллс Россия:
      - Отчет о подготовке и проведении демонстрационного экзамена по стандартам Ворлдскиллс и чемпионата по стандартам Ворлскиллс: start_point/wordsktls_2018_result.md
      
         

theme:
  name: 'material'
  language: 'ru'
  palette:
    primary: 'Blue'
    accent: 'Blue'
  feature:
    tabs: true
  logo: images/logo/logo_cut_white.png
  favicon: images/logo/favicon.ico